apiVersion: apps/v1
kind: Deployment
metadata: 
  name: meudeployment
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: converte
  template:
    metadata: 
      labels:
        app: converte
    spec: 
      containers:
        - name: converte
          image: rlsena/converte-temperatura:v1
          ports:
            - containerPort: 8080
---
apiVersion: v1 
kind: Service
metadata:
  name: service-web
spec:
  selector:
    app: converte
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30000
  type: NodePort